[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/jury-duty"
  to = "https://karinchung-juryduty.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/jury-duty/*"
  to = "https://karinchung-juryduty.netlify.app/:splat"
  status = 200
  force = true