[build]
  publish = "."

# Handle redirects first (more specific rules)
[[redirects]]
  from = "/jury-duty"
  to = "https://karinchung-juryduty.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/jury-duty/*"
  to = "https://karinchung-juryduty.netlify.app/:splat"
  status = 200
  force = true

# Handle main site routing last (more general rule)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200